
1.- Crea un diccionario que contenga 3 llaves que sean de tipo string y cuyos valores sean una lista que contenga 5 valores (3 numéricos y 2 flotantes).

2.- A partir del diccionario anterior, muestra a sus ítems. ¿Qué tipo de objeto se obtiene?

3.- Crea un panel de datos usando tu diccionario. Realiza tres segregaciones distintas.

4.- Realiza un breve análisis descriptivo de tu panel de datos. Explica los valores que obtienes.

5.- Realiza dos filtros de búsqueda sobre tu panel de datos.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Creamos la lista de datos a partir de la cual se va a crear el diccionario.
minutosentregoles1=(10,12,32,3.2,4.3)
minutosentregoles2=(12,34,32,2.1,2.2)
minutosentregoles3=(26,24,45,2.1,4.2)

In [ ]:
#1 Creamos el diccionario con las listas creadas previamente. Le damos un título a cada lista creada.
Dictionary={"Ronaldo":minutosentregoles1,"Neymar":minutosentregoles2,"Messi":minutosentregoles3}

In [ ]:
Dictionary

{'Ronaldo': (10, 12, 32, 3.2, 4.3),
 'Neymar': (12, 34, 32, 2.1, 2.2),
 'Messi': (26, 24, 45, 2.1, 4.2)}

In [ ]:
#2 Aquí podemos obervar el tipo de dato que se obtiene del diccionario creado antes.
type(Dictionary)

dict

In [ ]:
#3 A partir del diccionario que habíamos creado con las listas anteriores, ahora creamos una base de datos (dataframe) y le realizamos tres segregaciones.
#En las segregaciones, removimos la columna de Neymar y también removimos el renglón 0 y el renglón 4.

dataframe=pd.DataFrame(Dictionary)
dataframe

   Ronaldo  Neymar  Messi
0     10.0    12.0   26.0
1     12.0    34.0   24.0
2     32.0    32.0   45.0
3      3.2     2.1    2.1
4      4.3     2.2    4.2

In [ ]:
dataframe_segre=dataframe.drop(columns="Neymar")
dataframe_segre

   Ronaldo  Messi
0     10.0   26.0
1     12.0   24.0
2     32.0   45.0
3      3.2    2.1
4      4.3    4.2

In [ ]:
dataframe_segre=dataframe_segre.drop(0)
dataframe_segre

   Ronaldo  Messi
1     12.0   24.0
2     32.0   45.0
3      3.2    2.1
4      4.3    4.2

In [ ]:
dataframe_segre=dataframe_segre.drop(4)
dataframe_segre

   Ronaldo  Messi
1     12.0   24.0
2     32.0   45.0
3      3.2    2.1

In [ ]:
#4 Realizamos un análisis descriptivo del dataframe que se obtuvo después de las segregaciones realizadas. Se observa el número de datos, la media de ambas columnas,
#la desviación estándar, el dato menor de las columnas, el dato máximo de la columna.
dataframe_segre.describe()

         Ronaldo      Messi
count   3.000000   3.000000
mean   15.733333  23.700000
std    14.758500  21.451573
min     3.200000   2.100000
25%     7.600000  13.050000
50%    12.000000  24.000000
75%    22.000000  34.500000
max    32.000000  45.000000

In [ ]:
#5 Realizamos dos filtros de búsqueda sobre el dataframe creado anteriormente, en uno pedimos las columnas done "Messi" tenga un dato mayor a 20 y en
# el segundo pedimos las columnas donde "Ronaldo" tenga un dato menor a 10.
mayora20=dataframe_segre["Messi"]>20
filtrodataframe=dataframe_segre[mayora20]
filtrodataframe

   Ronaldo  Messi
1     12.0   24.0
2     32.0   45.0

In [ ]:
menora10=dataframe_segre["Ronaldo"]<10
segundofiltrodataframe=dataframe_segre[menora10]
segundofiltrodataframe

   Ronaldo  Messi
3      3.2    2.1